- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent
        force: yes
        purge: yes

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      docker_container:
        name: healthcareappdemo
        image: pawankalyan29/healthcareappdemo:v1
        state: started
        restart_policy: always
        published_ports:
          - "8086:8082"
